name: schemarecomb-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: pipx install poetry
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
    - name: Install dependencies and project
      run: |
        poetry install --no-interaction
    - name: Run tests
      run: |
        source .venv/bin/activate
        flake8 src/schemarecomb
        mypy src/schemarecomb
        mypy tests/unit
        pytest
